### ISSUE TITLE
Crash after successful face detection

### ISSUE THREAD

**Issue by george-aicenter** [darwinfrancis/viola#20]
Exception happens while using it with live stream.

Please find the details from logcat below.

`java.lang.IllegalArgumentException: width must be > 0
        at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:374)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:665)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:634)
        at com.darwin.viola.still.FaceAnalyser.cropFace(FaceAnalyser.kt:220)
        at com.darwin.viola.still.FaceAnalyser.processFace(FaceAnalyser.kt:96)
        at com.darwin.viola.still.FaceAnalyser.analyseMultipleFaces(FaceAnalyser.kt:70)
        at com.darwin.viola.still.FaceAnalyser.analyzeFaces(FaceAnalyser.kt:33)
        at com.darwin.viola.still.detector.FaceDetectorProcessor.onSuccess(FaceDetectorProcessor.kt:63)
        at com.darwin.viola.still.detector.FaceDetectorProcessor.onSuccess(FaceDetectorProcessor.kt:33)
        at com.darwin.viola.still.detector.VisionProcessorBase$requestDetectInImage$1.invoke(VisionProcessorBase.kt:48)
        at com.darwin.viola.still.detector.VisionProcessorBase$requestDetectInImage$1.invoke(VisionProcessorBase.kt:31)
        at com.darwin.viola.still.detector.TaskExtensionsKt$sam$com_google_android_gms_tasks_OnSuccessListener$0.onSuccess(TaskExtensions.kt)
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.darwin.viola.still.detector.ScopedExecutor$execute$1.run(ScopedExecutor.kt:44)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
`

**Comment by darwinfrancis** [comment]
Added try catch  on cropping the bitmap, this can prevent from crashes even though the input image has not the required area to perform crop. Fixed on version 1.1.4.
