### ISSUE TITLE
Crash when using cropFaceByLeastAlgorithm - not frequently

### ISSUE THREAD

**Issue by bassil-altamimi** [darwinfrancis/viola#9]
Non-fatal Exception: java.lang.IllegalArgumentException: x must be >= 0
       at android.graphics.Bitmap.checkXYSign(Bitmap.java:405)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:800)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:769)
       at com.darwin.viola.still.FaceAnalyser.cropFaceByLeastAlgorithm(FaceAnalyser.kt:246)
       at com.darwin.viola.still.FaceAnalyser.cropFace(FaceAnalyser.kt:125)
       at com.darwin.viola.still.FaceAnalyser.processFace(FaceAnalyser.kt:87)
       at com.darwin.viola.still.FaceAnalyser.analyseMultipleFaces(FaceAnalyser.kt:68)
       at com.darwin.viola.still.FaceAnalyser.analyzeFaces(FaceAnalyser.kt:32)
       at com.darwin.viola.still.detector.FaceDetectorProcessor.onSuccess(FaceDetectorProcessor.kt:63)
       at com.darwin.viola.still.detector.FaceDetectorProcessor.onSuccess(FaceDetectorProcessor.kt:33)
       at com.darwin.viola.still.detector.VisionProcessorBase$requestDetectInImage$1.invoke(VisionProcessorBase.kt:48)
       at com.darwin.viola.still.detector.VisionProcessorBase$requestDetectInImage$1.invoke(VisionProcessorBase.kt:31)
       at com.darwin.viola.still.detector.TaskExtensionsKt$sam$com_google_android_gms_tasks_OnSuccessListener$0.onSuccess(:2)
       at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
       at com.darwin.viola.still.detector.ScopedExecutor$execute$1.run(ScopedExecutor.kt:44)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6942)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by darwinfrancis** [comment]
Hi @bassil-altamimi could you please share with me the image file and the FaceOptions configuration which caused the exception.

**Comment by darwinfrancis** [comment]
Fixed on version 1.0.2

**Comment by bassil-altamimi** [comment]
Thx @darwinfrancis, I will check again and keep you posted!
